### PR TITLE
Added more fields to IPSec Phase 1 Interface

### PR DESCRIPTION
**Pull request by johnnyhuy**
Added the following additional fields to the `fortios_vpn_ipsec_phase1interface` Terraform resource block.

- `dh_group`
- `ike_version`
- `nat_traversal`
- `dead_peer_detection`

I've also cleaned up the test file in there and added one more case to acc test the new fields.

Please let me know if there needs more re-work 😀

### CODE REVIEW

**Comment by crawfs** [comment]
Hey @frankshen01 anything extra we need to be doing before this can be merged? Or is it just a waiting game at this point until you guys have the time to properly review it?

**Comment by frankshen01** [comment]
Hi @johnnyhuy , thanks for contributing to Terraform FortiOS provider. I’ve discussed with my manager on merging your PR. While your PR looks great, internally we've developed a new set of FortiOS resources that includes the feature you requested, so my manager suggests we use code from this new set to keep coding style consistent across all resources. The new code is under test now. The beta code for vpn ipsec phase1interface resource is here. https://github.com/fortinet-terraform-dev/terraform-provider-fortios-beta/blob/master/fortios/resource_vpnipsec_phase1interface.go. Could you check if it meets your requirement? Thanks for your great efforts and understanding!

**Comment by johnnyhuy** [comment]
Hey @frankshen01 , no problem. Is there any way we can directory use the beta provider from our Terraform templates?

**Comment by frankshen01** [comment]
hi @johnnyhuy  Appreciate your understanding. I've updated the repo's README with "A Quick Start Guide for Terraform Provider for FortiOS(Beta)"  for you just now. 
https://github.com/fortinet-terraform-dev/terraform-provider-fortios-beta
You can create issues in that repo when you need help, I will try to help. Thank you!

**Pull request closed without merging**
